site_name: Finoozer's Bookmark Collection
site_url: https://finoozer.github.io/bookmark-collection/
repo_url: https://github.com/Finoozer/bookmark-collection/
repo_name: Finoozer/bookmark-collection
edit_uri: edit/main/docs/
site_description: Smol bookmark collection, nothing important

plugins:
  - search

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences

theme:
  name: material
  favicon: assets/images/favicon.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - search.suggest
    - header.autohide
  icon:
    logo: material/library
    admonition:
      note: octicons/tag-16
  palette:
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: orange
        accent: light blue
        toggle:
          icon: material/weather-night
          name: Switch to dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate 
        primary: orange
        accent: light blue
        toggle:
          icon: material/weather-sunny
          name: Switch to light mode

nav:
    - Home: index.md
    - Learn:
      - learn/index.md
      - Read: learn/read.md
      - Watch: learn/watch.md
      - Podcasts: learn/podcasts.md
      - Courses: learn/courses.md
    - Tech: 
      - tech/index.md
      - News: tech/news.md
      - Tools: tech/tools.md
    - Coding:
      - coding/index.md
      - Javascript: coding/js.md
      - HTML: coding/html.md
      - Python: coding/python.md
    - InfoSec: 
      - infosec/index.md
      - News: infosec/news.md
    - OSes: 
      - os/index.md
      - Linux: os/linux.md
      - MacOS: os/macos.md
      - Windows: os/windows.md
    - Electrical Engineering: 
      - ee/index.md
    - 3D Printing/CAD: 
      - 3d/index.md
    - FAQ:
      - faq.md
    - Changelog:
      - changelog.md

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/finoozer
    - icon: fontawesome/brands/github
      link: https://github.com/Finoozer
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/_finoozer_/
