site_name: Finoozer's Bookmark Collection
site_url: https://finoozer.github.io/bookmark-collection/
repo_url: https://github.com/Finoozer/bookmark-collection/
repo_name: Finoozer/bookmark-collection
edit_uri: edit/main/docs/
site_description: Smol bookmark collection, nothing important

plugins:
  - search

markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - tables
  - footnotes
  - markdown.extensions.admonition
  - pymdownx.pathconverter:
      relative_path: 'docs/'
  - pymdownx.saneheaders
  - pymdownx.magiclink

theme:
  name: material
  favicon: assets/images/favicon.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - search.suggest
    - header.autohide
  icon:
    logo: material/library
  palette:
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: orange
        accent: light blue
        toggle:
          icon: material/weather-night
          name: Switch to dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate 
        primary: orange
        accent: light blue
        toggle:
          icon: material/weather-sunny
          name: Switch to light mode

nav:
    - Home: index.md
    - Tech:
      - Read: tech/read.md
      - Watch: tech/watch.md
      - Listen: tech/listen.md
      - Courses: tech/courses.md
      - News: tech/news.md
      - Tools: tech/tools.md
    - Coding:
      - Read: coding/read.md
      - Watch: coding/watch.md
      - Listen: coding/listen.md
      - Courses: coding/courses.md
      - Tools: coding/tools.md
      - Languages:
        - Javascript: coding/langs/js.md
        - HTML: coding/langs/html.md
        - CSS: coding/langs/css.md
        - Python: coding/langs/python.md
        - C#: coding/langs/csharp.md
    - InfoSec:
      - Read: infosec/read.md
      - Watch: infosec/watch.md
      - Listen: infosec/listen.md
      - News: infosec/news.md
      - Tools: infosec/tools.md
    - SysAdmin:
      - Read: sysadmin/read.md
      - Watch: sysadmin/watch.md
      - Listen: sysadmin/listen.md
      - News: sysadmin/news.md
      - Tools: sysadmin/tools.md
    - Electrical Engineering:
      - Read: ee/read.md
      - Watch: ee/watch.md
      - Listen: ee/listen.md
      - Tools: ee/tools.md
    - 3D Printing/CAD:
      - Read: 3d/read.md
      - Watch: 3d/watch.md
      - Tools: 3d/tools.md
    - Concepts:
      - concepts.md
    - FAQ:
      - faq.md

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/finoozer
    - icon: fontawesome/brands/github
      link: https://github.com/Finoozer
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/_finoozer_/
extra_css:
  - stylesheets/extra.css
